;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		cua-paste
		electric-verilog-tick
		indent-for-tab-command
		overwrite-mode
		))

(setq mc/cmds-to-run-once
      '(
		build-verilog-project
		cua-scroll-down
		cua-scroll-up
		duplicate-line
		electric-verilog-colon
		electric-verilog-semi
		iedit-switch-to-mc-mode
		))
